#!/usr/bin/env python3
"""Generate the two Kaggle kernel folders (C1 and C2) from the single source script.

Kaggle kernel metadata has no environment-variable field, and a pushed kernel runs with a
fixed environment, so `ARM` cannot be passed in at run time. Rather than keep two drifting
copies of the training script, this generates both from `train_c1_c2.py`, prefixing each
with the one line that pins the arm. The generated file states its arm on line 1, so a
kernel opened six months from now is self-identifying.

Output (gitignored, under tubitak/outputs/):
    tubitak/outputs/kaggle_build/c1/{train_c1_c2.py, kernel-metadata.json}
    tubitak/outputs/kaggle_build/c2/{train_c1_c2.py, kernel-metadata.json}

Then:
    kaggle kernels push -p tubitak/outputs/kaggle_build/c1
"""
import json
import os
import re

OWNER = "vedatyildirim"
DATASET = f"{OWNER}/gencp-tr"          # mounts at /kaggle/input/gencp-tr
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "train_c1_c2.py")
OUT = os.path.abspath(os.path.join(HERE, "..", "outputs", "kaggle_build"))

ARMS = {
    "C1": "GenCP Phase C - arm C1 (GAN + L1)",
    "C2": "GenCP Phase C - arm C2 (L1 only)",
    "C3": "GenCP Phase C - arm C3 (L1 only + EU mix)",
    # C4/C5: the LPIPS half of the 2x2 loss factorial (phase-c-lpips-registration.md).
    "C4": "GenCP Phase C - arm C4 (GAN + LPIPS)",
    "C5": "GenCP Phase C - arm C5 (LPIPS only)",
}


def slugify(title):
    """Reproduce Kaggle's own slug derivation.

    Discovered the hard way on 19 Aug 2026: `kernels push` does NOT create the kernel at the
    `id` in kernel-metadata.json. It slugifies the TITLE and uses that, warning only that the
    title "does not resolve to the specified id". The C1 push asked for `gencp-phase-c-c1`
    and got `gencp-phase-c-arm-c1-gan-l1`; `kernels status` on the requested id returns a
    permission error that reads like a private-notebook problem, not a missing one.

    Deriving the id FROM the title makes the two impossible to disagree, so a re-push updates
    the existing kernel instead of silently creating a second one.
    """
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", title.lower())).strip("-")

# Seeds to emit. 42 is the completed package and is emitted unsuffixed so a re-push updates
# the existing kernels rather than creating parallel ones. 43+ are the replication package
# (tubitak/docs/seed-replication-registration.md): the training seed is the only manipulated
# factor, and it varies the cold-D draw in the adversarial arms by intent. Titles carry the
# seed because Kaggle derives the kernel slug from the TITLE (see slugify) - without it, two
# seeds of one arm would collide on one kernel and the second push would overwrite the first.
SEEDS = [int(x) for x in os.environ.get("SEEDS", "43,44").split(",")]

with open(SRC, encoding="utf-8") as f:
    body = f.read()

# The 2x2 factorial is C1/C2/C4/C5. C3 (EU mix) is not a cell of it and is not replicated
# across seeds; it stays a seed-42-only arm so the replication package emits exactly the
# eight runs the registration schedules.
FACTORIAL = ("C1", "C2", "C4", "C5")

for arm, base_title in ARMS.items():
    for seed in SEEDS:
        if seed != 42 and arm not in FACTORIAL:
            continue
        title = base_title if seed == 42 else f"{base_title} seed {seed}"
        slug = slugify(title)
        folder = os.path.join(OUT, arm.lower() if seed == 42 else f"{arm.lower()}_s{seed}")
        os.makedirs(folder, exist_ok=True)

        header = (
            f"# GENERATED by tubitak/kaggle/build_kernels.py - do not edit here.\n"
            f"# Edit tubitak/kaggle/train_c1_c2.py and regenerate.\n"
            f"# This copy is pinned to arm {arm}, seed {seed}.\n"
            f'import os; os.environ["ARM"] = "{arm}"; os.environ["SEED"] = "{seed}"\n\n'
        )
        with open(os.path.join(folder, "train_c1_c2.py"), "w", encoding="utf-8") as f:
            f.write(header + body)

        meta = {
            "id": f"{OWNER}/{slug}",
            "title": title,
            "code_file": "train_c1_c2.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,          # verified again from inside the kernel by preflight()
            "enable_tpu": False,
            "enable_internet": True,     # git clone + pip install + LPIPS VGG weight download
            # Pin the accelerator. Left generic ("Gpu"), Kaggle handed the first C1 push a Tesla
            # P100 (sm_60), which this image's torch 2.10.0+cu128 cannot emit code for - it builds
            # for sm_70 and up. T4 is sm_75 and verified working (matmul + conv) by the probe.
            "machine_shape": "NvidiaTeslaT4",
            "dataset_sources": [DATASET],
            "competition_sources": [],
            "kernel_sources": [],
            "model_sources": [],
        }
        with open(os.path.join(folder, "kernel-metadata.json"), "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)
            f.write("\n")

        print(f"{arm} seed {seed}: {folder}  ->  {meta['id']}")
